version: "3"
services:
  develop:
    build: .
    volumes:
      - .:/app
    ports:
      - 4000:4000
      - 35729:35729
    command: bundle exec jekyll serve -H 0.0.0.0 -P 4000 --livereload
volumes:
  local_bundle:
